sources:
  - name: source
    database: dbt_tutorial_dev  
    schema: source  
    tables:
      - name: dim_date
      - name: dim_product
      
      - name: dim_store
      - name: dim_customer

      - name: fact_sales
      - name: fact_returns

      - name: items

