dbt_tutorial:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: dbc-0661453f-677f.cloud.databricks.com
      http_path: /sql/1.0/warehouses/750a17b3ac6f32e6
      schema: default
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
  


    prod:
      catalog: dbt_tutorial_prod
      host: dbc-0661453f-677f.cloud.databricks.com
      http_path: /sql/1.0/warehouses/750a17b3ac6f32e6
      schema: default
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev


    
